roger_plast_prod_homepage:
    path:     /
    defaults: { _controller: ROGERPlastProdBundle:PlastProd:index }

roger_plast_prod_clients:
    path:    /Client
    defaults: { _controller: ROGERPlastProdBundle:Client:client}

roger_plast_prod_client_suivi:
    path:    /Client/Suivi
    defaults: { _controller:ROGERPlastProdBundle:Client:suivi}

roger_plast_prod_client_infos:
    path: /Client/Infos
    defaults: { _controller:ROGERPlastProdBundle:Client:infos}

roger_plast_prod_client_communique:
    path: /Client/Contact
    defaults: { _controller:ROGERPlastProdBundle:Client:communique}

roger_plast_prod_production:
    path: /Production
    defaults: { _controller: ROGERPlastProdBundle:Production:production}

roger_plast_prod_production_lancement:
    path:    /Production/LancerProd
    defaults: { _controller: ROGERPlastProdBundle:Production:lancement}

roger_plast_prod_production_etiquette:
    path:   /Production/Etiquettes
    defaults: { _controller: ROGERPlastProdBundle:Production:etiquette}

roger_plast_prod_production_jeter:
    path:    /Production/ProduitsDefaillants
    defaults: { _controller: ROGERPlastProdBundle:Production:jeter}

roger_plast_prod_fournisseurs:
    path:    /Fournisseurs
    defaults: { _controller: ROGERPlastProdBundle:Fournisseurs:fournisseurs}

roger_plast_prod_stocks:
    path:    /Stocks
    defaults: { _controller: ROGERPlastProdBundle:Stocks:index}

roger_plast_prod_stocks_nomenclature:
    path:    /Stocks/GestionsNomenclatures
    defaults: { _controller: ROGERPlastProdBundle:Stocks:nomenclature}


roger_plast_prod_stocks_stockage:
    path:    /Stocks/GestionNomenclature/Stockage
    defaults: { _controller: ROGERPlastProdBundle:Stocks:stockage}

roger_plast_prod_stocks_expedition:
    path:   /Stocks/GestionNomenclature/Expeditions
    defaults: { _controller: ROGERPlastProdBundle:Stocks:expedition}

roger_plast_prod_stocks_gestionMP:
    path:    /Stocks/GestionMP
    defaults: { _controller: ROGERPlastProdBundle:Stocks:gestionMP}

roger_plast_prod_stocks_MP:
    path:    /Stocks/MatieresPremieres
    defaults: { _controller: ROGERPlastProdBundle:Stocks:matieres}


roger_plast_prod_stocks_MP_Inventaire:
    path:    /Stocks/MatieresPremieres/Inventaire
    defaults: { _controller: ROGERPlastProdBundle:Stocks:inventaire }


roger_plast_prod_config:
    path:    /Config
    defaults: {_controller: ROGERPlastProdBundle:Config:index}

roger_plast_prod_config_acces:
    path:    /Config/Acces
    defaults: { _controller: ROGERPlastProdBundle:Config:acces}

roger_plast_prod_config_droits:
    path:    /Config/Droits
    defaults: { _controller: ROGERPlastProdBundle:Config:droits}

roger_plast_prod_config_ajout:
    path:    /Config/Ajout
    defaults: { _controller: ROGERPlastProdBundle:Config:add}
