<?php

namespace Proxies\__CG__\ROGER\PlastProdBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Nomenclature extends \ROGER\PlastProdBundle\Entity\Nomenclature implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'ROGER\\PlastProdBundle\\Entity\\Nomenclature' . "\0" . 'id', '' . "\0" . 'ROGER\\PlastProdBundle\\Entity\\Nomenclature' . "\0" . 'affectation_matiere', '' . "\0" . 'ROGER\\PlastProdBundle\\Entity\\Nomenclature' . "\0" . 'nom', '' . "\0" . 'ROGER\\PlastProdBundle\\Entity\\Nomenclature' . "\0" . 'cheminDoc', '' . "\0" . 'ROGER\\PlastProdBundle\\Entity\\Nomenclature' . "\0" . 'tempsProduction', '' . "\0" . 'ROGER\\PlastProdBundle\\Entity\\Nomenclature' . "\0" . 'tempsAssemblage');
        }

        return array('__isInitialized__', '' . "\0" . 'ROGER\\PlastProdBundle\\Entity\\Nomenclature' . "\0" . 'id', '' . "\0" . 'ROGER\\PlastProdBundle\\Entity\\Nomenclature' . "\0" . 'affectation_matiere', '' . "\0" . 'ROGER\\PlastProdBundle\\Entity\\Nomenclature' . "\0" . 'nom', '' . "\0" . 'ROGER\\PlastProdBundle\\Entity\\Nomenclature' . "\0" . 'cheminDoc', '' . "\0" . 'ROGER\\PlastProdBundle\\Entity\\Nomenclature' . "\0" . 'tempsProduction', '' . "\0" . 'ROGER\\PlastProdBundle\\Entity\\Nomenclature' . "\0" . 'tempsAssemblage');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Nomenclature $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setCheminDoc($cheminDoc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCheminDoc', array($cheminDoc));

        return parent::setCheminDoc($cheminDoc);
    }

    /**
     * {@inheritDoc}
     */
    public function getCheminDoc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCheminDoc', array());

        return parent::getCheminDoc();
    }

    /**
     * {@inheritDoc}
     */
    public function setTempsProduction($tempsProduction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTempsProduction', array($tempsProduction));

        return parent::setTempsProduction($tempsProduction);
    }

    /**
     * {@inheritDoc}
     */
    public function getTempsProduction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTempsProduction', array());

        return parent::getTempsProduction();
    }

    /**
     * {@inheritDoc}
     */
    public function setTempsAssemblage($tempsAssemblage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTempsAssemblage', array($tempsAssemblage));

        return parent::setTempsAssemblage($tempsAssemblage);
    }

    /**
     * {@inheritDoc}
     */
    public function getTempsAssemblage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTempsAssemblage', array());

        return parent::getTempsAssemblage();
    }

}
