<?php

namespace ROGER\PlastProdBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FournisseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FournisseurRepository extends EntityRepository
{
	public function getAllFournisseurs()
	{
		// Création du query builder
		$queryBuilder = $this->createQueryBuilder('f');
		
		// Récupération de la réquête
		$query = $queryBuilder->getQuery();
		
		// Récupération du résultat de la requête
		$results = $query->getResult();
		
		return $results;
		
	}
}
