<?php

namespace ROGER\PlastProdBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MatiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatiereRepository extends EntityRepository
{
	public function getAllMatieres()
	{
			$queryBuilder = $this->_em->createQueryBuilder()
													->select('n')
													->from($this->_entityName, 'n');
		$query = $queryBuilder->getQuery();
		$results  = $query->getResult();
		
		return $results;
	}
}
